RedeSocial/RedeSocial.Web/Models/AccountApi/CriarAccountViewModel.cs
using Microsoft.AspNetCore.Http;
using RedeSocial.Domain.Account;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RedeSocial.Web.Models.Account
{
    public class CriarAccountViewModel
    {
        [Required(ErrorMessage = "Nome é um campo obrigátorio")]
        public String Name { get; set; }
        [Required(ErrorMessage = "Data aniversario é um campo obrigátorio")]
        public DateTime DtBirthday { get; set; }
        [Required(ErrorMessage = "Email é um campo obrigátorio")]
        public String Email { get; set; }
        [Required(ErrorMessage = "password é um campo obrigátorio")]
        public String Password { get; set; }
        public Role Role { get; set; }
        [Required(ErrorMessage = "Username é um campo obrigátorio")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "Foto é um campo obrigátorio")]
        public IFormFile fotoAccount { get; set; }
        public string fotoPerfil { get; set; }
    }
}

RedeSocial/RedeSocial.Web/Models/AccountApi/DeletarAccountViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedeSocial.Web.Models.Account
{
    public class DeletarAccountViewModel
    {
    }
}

RedeSocial/RedeSocial.Web/Models/AccountApi/DetalharAccountViewModel.cs
using Microsoft.AspNetCore.Http;
using RedeSocial.Domain.Account;
using System;

namespace RedeSocial.Web.Models.Account
{
    public class DetalharAccountViewModel
    {
        public string Id { get; set; }
        public String Name { get; set; }
        public DateTime DtBirthday { get; set; }
        public String Email { get; set; }
        public String Password { get; set; }
        public Role Role { get; set; }
        public string UserName { get; set; }
        public string fotoPerfil { get; set; }
    }
}

RedeSocial/RedeSocial.Web/Models/AccountApi/EditarAccountViewModel.cs
using RedeSocial.Domain.Account;
using System;

namespace RedeSocial.Web.Models.Account
{
    public class EditarAccountViewModel
    {
        public string Id { get; set; }
        public String Name { get; set; }
        public DateTime DtBirthday { get; set; }
        public String Email { get; set; }
        public String Password { get; set; }
        public Role Role { get; set; }
        public string UserName { get; set; }
        public string fotoPerfil { get; set; }
    }
}

RedeSocial/RedeSocial.Web/Models/AccountApi/ListarAccountViewModel.cs
using Microsoft.AspNetCore.Http;
using RedeSocial.Domain.Account;
using System;

namespace RedeSocial.Web.Models.Account
{
    public class ListarAccountViewModel
    {
        public string Id { get; set; }
        public String Name { get; set; }
        public DateTime DtBirthday { get; set; }
        public String Email { get; set; }
        public String Password { get; set; }
        public Role Role { get; set; }
        public string UserName { get; set; }
        public string fotoPerfil { get; set; }
    }
}

RedeSocial/RedeSocial.Web/Controllers/AccountApiController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Storage.Blob;
using RedeSocial.Web.Models.Account;
using WebApp.ApiServices;

namespace  RedeSocial.Web.Controllers

{
    public class AccountApiController : Controller
    {
        private readonly IAccountApi _accountApi;

        public AccountApiController(IAccountApi accountApi)
        {
            _accountApi = accountApi;
        }

        // GET: PaisesController
        public async Task<ActionResult> Index()
        {
            var accounts = await _accountApi.GetAsync();

            return View(accounts);
        }

        // GET: PaisesController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var viewModel = await _accountApi.GetAsync(id);

            return View(viewModel);
        }

        // GET: PaisesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PaisesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CriarAccountViewModel criarAccountViewModel)
        {
            await _accountApi.PostAsync(criarAccountViewModel);

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: PaisesController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var viewModel = await _accountApi.GetAsyncToEdit(id);

            return View(viewModel);
        }

        // POST: PaisesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, EditarAccountViewModel editarAccountViewModel)
        {
            await _accountApi.EditAsync( id ,editarAccountViewModel);
            try
            {

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: PaisesController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var viewModel = await _accountApi.GetAsyncToDelete(id);

            return View(viewModel);
        }

        // POST: PaisesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, DeletarAccountViewModel deletarAccountViewModel)
        {
            await _accountApi.DeleteAsync(id);
            try
            {
                return RedirectToAction("Login", "Account");
            }
            catch
            {
                return View();
            }
        }
        private string UploadFotoPerfil(IFormFile fotoAccount)
        {


            var reader = fotoAccount.OpenReadStream();
            var cloudStorageAccount = Microsoft.Azure.Storage.CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=redesocialverde;AccountKey=ZkwgagZSBq16yjP/iPVd6228IfEO63Q1+e94/SQ2PbeKSAFiKlyL6N8oU7cfuqVekwNxvrLcdY64VkhlBOgMQw==;EndpointSuffix=core.windows.net");
            var blobClient = cloudStorageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("fotoperfil");
            container.CreateIfNotExists();
            var blob = container.GetBlockBlobReference(Guid.NewGuid().ToString());
            blob.UploadFromStream(reader);
            var destinoDaImagemNaNuvem = blob.Uri.ToString();
            return destinoDaImagemNaNuvem;
        }
    }
}

RedeSocial/RedeSocial.Web/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RedeSocial.CrossCutting.Storage;

namespace RedeSocial.Web.Controllers
{
    public class UploadController : Controller
    {
        private AzureStorage AzureStorage { get; set; }

        public UploadController(AzureStorage azureStorage)
        {
            AzureStorage = azureStorage;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] IFormFile file)
        {
            var ms = new MemoryStream();

            if (file.ContentType.ToLower() != "image/jpg" && file.ContentType.ToLower() != "image/jpeg" && file.ContentType.ToLower() != "image/png" && file.ContentType.ToLower() != "image/bmp")
            {
                ModelState.AddModelError("Image", "Image deve ser com a extensão .jpg, .png ou bmp");
                return View();
            }

            using (var fileUpload = file.OpenReadStream())
            {
                await fileUpload.CopyToAsync(ms);
                fileUpload.Close();
            }

            var urlAzure = await this.AzureStorage.SaveToStorage(ms.ToArray(), $"{Guid.NewGuid().ToString().Replace("-", "")}.jpg");

            ViewBag.UrlGerada = urlAzure;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateFotoPerfil([FromForm] IFormFile file)
        {
            var ms = new MemoryStream();

            if (file.ContentType.ToLower() != "image/jpg" && file.ContentType.ToLower() != "image/jpeg" && file.ContentType.ToLower() != "image/png" && file.ContentType.ToLower() != "image/bmp")
            {
                ModelState.AddModelError("Image", "Image deve ser com a extensão .jpg, .png ou bmp");
                return View();
            }

            using (var fileUpload = file.OpenReadStream())
            {
                await fileUpload.CopyToAsync(ms);
                fileUpload.Close();
            }

            var urlAzure = await this.AzureStorage.SaveToStorage(ms.ToArray(), $"{User.Identity.Name.ToString().Replace("-", "")}fotoperfil.jpg");

            ViewBag.UrlGerada = urlAzure;

            return View("/Views/Home/index.cshtml");
        }

    }
}

RedeSocial/RedeSocial.Web/Views/AccountApi/Create.cshtml
@model RedeSocial.Web.Models.Account.CriarAccountViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Cadastrar Conta</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DtBirthday" class="control-label">Data de Aniversario</label>
                <input asp-for="DtBirthday" type="date" class="form-control" />
                <span asp-validation-for="DtBirthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

    <div>
        <a asp-action="Index">Voltar para a lista</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

RedeSocial/RedeSocial.Web/Views/AccountApi/Delete.cshtml
@model RedeSocial.Domain.Account.Account

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Account</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DtBirthday)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DtBirthday)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.fotoPerfil)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.fotoPerfil)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

RedeSocial/RedeSocial.Web/Views/AccountApi/Edit.cshtml
@model RedeSocial.Web.Models.Account.EditarAccountViewModel

@{ ViewData["Title"] = "Edit"; }
<h4>Foto de Perfil</h4>
<img class="img-thumbnail"
     src="https://redesocialverde.blob.core.windows.net/imagens/@(this.User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.Name).Value)fotoperfil.jpg?size=30x30&bgset=bg1">

<h1>Edit</h1>

<h4>Account</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DtBirthday" class="control-label"></label>
                <input asp-for="DtBirthday" class="form-control" />
                <span asp-validation-for="DtBirthday" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<h4>Trocar foto de perfil</h4>

@if (ViewBag.UrlGerada != null)
{
<img src="@ViewBag.UrlGerada" />}
<form asp-action="CreateFotoPerfil" asp-controller="Upload" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label>Arquivo</label>
        <input type="file" class="form-control" placeholder="file" name="file" id="file">
    </div>
    <button type="submit" class="btn btn-primary">Entrar</button>
</form>

<div>
    <a asp-controller="Home" asp-action="Index">Voltar ao menu</a>
</div>


<td>
    <a asp-route-id="@Model.Id" asp-action="Delete">Deletar</a>
</td>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RedeSocial/RedeSocial.Web/Views/AccountApi/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Conta criada com SUCESSO!!</h1>
<br />

<br />

<h3>
    <a asp-controller="Account" asp-action="Login">Login</a>
</h3>