RedeSocial/RedeSocial.Web/Models/PostagemApi/CriarPostagemViewModel.cs
using Microsoft.AspNetCore.Http;
using RedeSocial.Domain.Account;
using System;
using System.Collections.Generic;

namespace RedeSocial.Web.Models.PostagemApi
{
    public class CriarPostagemViewModel
    {
        public string titulo { get; set; }
        public string urlFotoPost { get; set; }
        public IFormFile fotoPost { get; set; }
        public string legenda { get; set; }
        public Guid accountId { get; set; }
        public string accountName { get; set; }
        public List<Comentario> Comentario { get; set; }
    }
}

RedeSocial/RedeSocial.Web/Models/PostagemApi/DeletarPostagemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedeSocial.Web.Models.PostagemApi
{
    public class DeletarPostagemViewModel
    {
    }
}

RedeSocial/RedeSocial.Web/Models/PostagemApi/EditarPostagemViewModel.cs
using RedeSocial.Domain.Account;
using System;
using System.Collections.Generic;

namespace RedeSocial.Web.Models.PostagemApi
{
    public class EditarPostagemViewModel
    {
        public Guid postagemId { get; set; }
        public string titulo { get; set; }
        public string urlFotoPost { get; set; }
        public string legenda { get; set; }
        public Guid accountId { get; set; }
        public List<Comentario> Comentario { get; set; }
    }
}

RedeSocial/RedeSocial.Web/Models/PostagemApi/ListarPostagemViewModel.cs
using RedeSocial.Domain.Account;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RedeSocial.Web.Models.PostagemApi
{
    public class ListarPostagemViewModel
    {
        public Guid postagemId { get; set; }
        public string titulo { get; set; }
        public string urlFotoPost { get; set; }
        public string legenda { get; set; }
        public Guid accountId { get; set; }
        public List<Comentario> Comentario { get; set; }
    }
}

RedeSocial/RedeSocial.Web/Controllers/ComentarioApiController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Storage.Blob;
using RedeSocial.Domain.Account;
using RedeSocial.Web.Models.ComentarioApi;
using RedeSocial.Web.Models.PostagemApi;
using Ubiety.Dns.Core;
using WebApp.ApiServices;

namespace  RedeSocial.Web.Controllers

{
    public class ComentarioApiController : Controller
    {
        private readonly IComentarioApi _comentariomApi;
        private readonly IAccountApi _accountApi;


        public ComentarioApiController(IComentarioApi comentariomApi, IAccountApi accountapi)
        {
            _comentariomApi = comentariomApi;
            _accountApi = accountapi;
        }

        // GET: PaisesController
        public async Task<ActionResult> Index(string id)
        {
            var separadoid = id.Split("&&");
            var userId = separadoid[0];
            var postId = separadoid[1];
            var coments = await _comentariomApi.GetAsync(userId, postId);

            return View(coments);
        }

        


        // GET: PaisesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PaisesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CriarComentarioViewModel criarComentarioViewModel, Guid id)
        {
           
            Guid postId = id;
            await _comentariomApi.PostAsync(criarComentarioViewModel, postId);

            try
            {
                return RedirectToAction("Index", "PostagemApi");
            }
            catch
            {
                return View();
            }
        }



        // GET: PaisesController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var viewModel = await _comentariomApi.GetAsyncToEdit(id);

            return View(viewModel);
        }

        // POST: PaisesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, Comentario comentarios)
        {
            await _comentariomApi.EditAsync( id , comentarios);
            try
            {
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PaisesController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var separadoid = id.Split("&&");
            var comentId = separadoid[0];
            var postId = separadoid[1];
            //var viewModel = await _comentariomApi.GetAsyncEspecifico(comentId, postId);
            await _comentariomApi.DeleteAsync(comentId, postId);

            return RedirectToAction(nameof(Index));
        }

        // POST: PaisesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, Postagem postagem)
        {
            var separadoid = id.Split("&&");
            var postId = separadoid[0];
            var userId = separadoid[1];
            await _comentariomApi.DeleteAsync(userId, postId);
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        private string UploadFotoPerfil(IFormFile fotoPost)
        {


            var reader = fotoPost.OpenReadStream();
            var cloudStorageAccount = Microsoft.Azure.Storage.CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=redesocialverde;AccountKey=ZkwgagZSBq16yjP/iPVd6228IfEO63Q1+e94/SQ2PbeKSAFiKlyL6N8oU7cfuqVekwNxvrLcdY64VkhlBOgMQw==;EndpointSuffix=core.windows.net");
            var blobClient = cloudStorageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("fotoperfil");
            container.CreateIfNotExists();
            var blob = container.GetBlockBlobReference(Guid.NewGuid().ToString());
            blob.UploadFromStream(reader);
            var destinoDaImagemNaNuvem = blob.Uri.ToString();
            return destinoDaImagemNaNuvem;
        }
    }

}

RedeSocial/RedeSocial.Web/Controllers/PostagemApiController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Storage.Blob;
using RedeSocial.Domain.Account;
using RedeSocial.Web.Models.PostagemApi;
using Ubiety.Dns.Core;
using WebApp.ApiServices;

namespace  RedeSocial.Web.Controllers

{
    public class PostagemApiController : Controller
    {
        private readonly IPostagemApi _postagemApi;
        private readonly IAccountApi _accountApi;

        public PostagemApiController(IPostagemApi postagemApi, IAccountApi accountapi)
        {
            _postagemApi = postagemApi;
            _accountApi = accountapi;
        }

        // GET: PaisesController
        public async Task<ActionResult> Index(string id)
        {
            var accounts = await _postagemApi.GetAsync();

            return View(accounts);
        }

        


        // GET: PaisesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PaisesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CriarPostagemViewModel criarPostagemViewModel)
        {
            var URLFoto = UploadFotoPerfil(criarPostagemViewModel.fotoPost);
            criarPostagemViewModel.urlFotoPost = URLFoto;
            
            await _postagemApi.PostAsync(criarPostagemViewModel);

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: PaisesController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var viewModel = await _postagemApi.GetAsyncToEdit(id);

            return View(viewModel);
        }

        // POST: PaisesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, EditarPostagemViewModel editarPostagemViewModel)
        {
            await _postagemApi.EditAsync( id , editarPostagemViewModel);
            try
            {
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PaisesController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var separadoid = id.Split("&&");
            var postId = separadoid[0];
            var userId = separadoid[1];
            var viewModel = await _postagemApi.GetAsync(userId, postId);

            return View(viewModel);
        }

        // POST: PaisesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, Postagem postagem)
        {
            var separadoid = id.Split("&&");
            var postId = separadoid[0];
            var userId = separadoid[1];
            await _postagemApi.DeleteAsync(userId, postId);
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        private string UploadFotoPerfil(IFormFile fotoPost)
        {


            var reader = fotoPost.OpenReadStream();
            var cloudStorageAccount = Microsoft.Azure.Storage.CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=redesocialverde;AccountKey=ZkwgagZSBq16yjP/iPVd6228IfEO63Q1+e94/SQ2PbeKSAFiKlyL6N8oU7cfuqVekwNxvrLcdY64VkhlBOgMQw==;EndpointSuffix=core.windows.net");
            var blobClient = cloudStorageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("fotoperfil");
            container.CreateIfNotExists();
            var blob = container.GetBlockBlobReference(Guid.NewGuid().ToString());
            blob.UploadFromStream(reader);
            var destinoDaImagemNaNuvem = blob.Uri.ToString();
            return destinoDaImagemNaNuvem;
        }
    }
}

RedeSocial/RedeSocial.Web/Views/PostagemApi/Create.cshtml
@model RedeSocial.Web.Models.PostagemApi.CriarPostagemViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Postagem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="titulo" class="control-label"></label>
                <input asp-for="titulo" class="form-control" />
                <span asp-validation-for="titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="legenda" class="control-label"></label>
                <input asp-for="legenda" class="form-control" />
                <span asp-validation-for="legenda" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="accountId" value="@(this.User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value)" ; />
                <span asp-validation-for="accountId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="hidden" asp-for="accountName" value="@(this.User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.Name).Value)" ; />
                <span asp-validation-for="accountName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="fotoPost" class="control-label"></label>
                <input type="file" name="fotoPost" for="nome" class="form-control" />
                <span validation-for="fotoPost" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

RedeSocial/RedeSocial.Web/Views/PostagemApi/Delete.cshtml
@model RedeSocial.Domain.Account.Postagem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>

    <h1>Deletar este post?</h1>
    <article class="card">
        <div class="card__wrapper">

            <figure class="card__feature">
                <img src="@Html.DisplayFor(model => model.urlFotoPost)" class="card__img" alt="Bridge" width="275" height="240">
            </figure>

            <div class="card__box">

                <header class="card__item card__header">
                    <h2 class="card__item card__item--small card__title">@Html.DisplayFor(model => model.titulo)</h2>
                </header>

                <hr class="card__item card__divider">

                <section class="card__item card__body">
                    <p>@Html.DisplayFor(model => model.legenda)</p>
                </section>

            </div>

        </div>
    </article>

    <form asp-action="Delete">
        <input type="hidden" asp-for="postagemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
<style>
    /* Block */
    .card {
        width: 300px;
        font-family: 'Playfair Display', serif;
        text-align: center;
        transition: all .125s;
        transform: scale(1) translateY(0px);
    }

    /* Elements */
    .card__wrapper {
        padding-top: .1px;
        padding-bottom: .1px;
        position: relative;
        background-color: #ffffff;
        color: #999999;
        box-shadow: 0 0 5px 0 rgba(0,0,0,.05);
    }

        .card__wrapper:after {
            content: '';
            position: absolute;
            z-index: -1;
            top: 15px;
            right: 15px;
            bottom: 0;
            left: 15px;
            box-shadow: 0 5px 15px 0 rgba(0,0,0,.2);
            transition: all .125s;
            transform: scale(1) translateY(0px);
        }

    .card__box {
        padding-right: 35px;
        padding-left: 35px;
        margin-top: 25px;
        margin-bottom: 25px;
    }

    .card__item {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .card__item--small {
        margin-top: 10px;
        margin-bottom: 10px;
    }

    .card__feature {
        margin-top: 0;
        margin-right: 0;
        margin-bottom: 0;
        margin-left: 0;
    }

    .card__img {
        display: block;
        max-width: 100%;
        height: 280px;
        width: 300px;
    }

    .card__header {
        position: relative;
        z-index: 1;
    }

    .card__title {
        color: #222222;
        font-size: 30px;
        font-weight: 400;
        line-height: 1.25;
    }

    .card__label {
        color: #cccccc;
        font-family: 'Montserrat', sans-serif;
        font-size: 8px;
        text-transform: uppercase;
        letter-spacing: .2em;
    }

    .card__divider {
        display: block;
        width: 100%;
        height: 15px;
        border: none;
        background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiIHdpZHRoPSIyOHB4IiBoZWlnaHQ9IjE1cHgiIHZpZXdCb3g9IjAgMCAyOCAxNSIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjggMTUiIHhtbDpzcGFjZT0icHJlc2VydmUiPjxwYXRoIGZpbGw9IiNERURFREUiIGQ9Ik0yNy41LDdoLTZDMjEuMiwzLjEsMTgsMCwxNCwwUzYuOCwzLjEsNi41LDdoLTZDMC4yLDcsMCw3LjIsMCw3LjVTMC4yLDgsMC41LDhoNmMwLjMsMy45LDMuNSw3LDcuNSw3czcuMi0zLjEsNy41LTdoNkMyNy44LDgsMjgsNy44LDI4LDcuNVMyNy44LDcsMjcuNSw3eiBNMTQsMWMzLjQsMCw2LjIsMi42LDYuNSw2SDcuNUM3LjgsMy42LDEwLjYsMSwxNCwxeiBNMTQsMTRjLTMuNCwwLTYuMi0yLjYtNi41LTZoMTIuOUMyMC4yLDExLjQsMTcuNCwxNCwxNCwxNHoiLz48L3N2Zz4=);
        background-repeat: no-repeat;
        background-position: center center;
    }

    .card__body {
        font-size: 16px;
        line-height: 1.75;
    }

    /* Modifiers */
    .card:hover {
        cursor: pointer;
        transform: scale(1.05);
    }

        .card:hover .card__wrapper {
            box-shadow: 0 0 10px 0 rgba(0,0,0,.05);
        }

            .card:hover .card__wrapper:after {
                transform: scale(0.95) translateY(10px);
            }

    /* Demo */
    body {
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        background-color: #e9ebea;
        text-align: center;
    }

    .card {
        display: inline-block;
        margin-top: calc( ( 100vh - 506px ) / 2 );
        margin-right: 15px;
        margin-left: 15px;
        top: 50%;
    }
</style>

RedeSocial/RedeSocial.Web/Views/PostagemApi/Index.cshtml
@model IEnumerable<RedeSocial.Domain.Account.Postagem>

@{
    ViewData["Title"] = "Index";
}

<h1>
    <a asp-controller="PostagemApi" asp-action="Create">Postar Algo</a>
</h1>
@foreach (var item in Model)
{
    var accountid = item.accountId.ToString();
    var account2 = this.User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value;
    <article class="card">
        <div class="card__wrapper">

            <figure class="card__feature">
                <img src="@Html.DisplayFor(modelItem => item.urlFotoPost)" class="card__img" alt="Bridge" width="275" height="240">
            </figure>

            <div class="card__box">

                <header class="card__item card__header">
                    <h6 class="card__item card__item--small card__label"style="font-size:18px">@Html.DisplayFor(modelItem => item.accountName)</h6>
                    <h6 class="card__item card__item--small card__label">@if (accountid == account2)
                    {<a asp-action="Delete" asp-route-id="@item.postagemId&&@item.accountId">Deletar post</a>}</h6>
                    <h2 class="card__item card__item--small card__title">@Html.DisplayFor(modelItem => item.titulo)</h2>

                </header>

                <hr class="card__item card__divider">

                <section class="card__item card__body">
                    <p>@Html.DisplayFor(modelItem => item.legenda)</p>
                    <a asp-controller="ComentarioApi" asp-action="Index" asp-route-id="@item.accountId&&@item.postagemId">Comentar</a>
                </section>

            </div>

        </div>
    </article>

}
<style>
    /* Block */
    .card {
        width: 500px;
        height:500px;
        font-family: 'Playfair Display', serif;
        text-align: center;
        transition: all .125s;
        transform: scale(1) translateY(0px);
    }

    /* Elements */
    .card__wrapper {
        padding-top: .1px;
        padding-bottom: .1px;
        position: relative;
        background-color: #ffffff;
        color: #999999;
        box-shadow: 0 0 5px 0 rgba(0,0,0,.05);
    }

        .card__wrapper:after {
            content: '';
            position: absolute;
            z-index: -1;
            top: 15px;
            right: 15px;
            bottom: 0;
            left: 15px;
            box-shadow: 0 5px 15px 0 rgba(0,0,0,.2);
            transition: all .125s;
            transform: scale(1) translateY(0px);
        }

    .card__box {
        padding-right: 35px;
        padding-left: 35px;
        margin-top: 15px;
        margin-bottom: 25px;
    }

    .card__item {
        margin-top: 20px;
        margin-bottom: 20px;
    }

    .card__item--small {
        margin-top: 10px;
        margin-bottom: 10px;
    }

    .card__feature {
        margin-top: 0;
        margin-right: 0;
        margin-bottom: 0;
        margin-left: 0;
    }

    .card__img {
        display: block;
        max-width: 100%;
        height: 350px;
        width: 500px;
    }

    .card__header {
        position: relative;
        z-index: 1;
    }

    .card__title {
        color:darkslategrey;
        font-size: 30px;
        font-weight: 400;
        line-height: 1.25;
    }

    .card__label {
        color: #cccccc;
        font-family: 'Montserrat', sans-serif;
        font-size: 8px;
        text-transform: uppercase;
        letter-spacing: .2em;
    }

    .card__divider {
        display: block;
        width: 100%;
        height: 15px;
        border: none;
        background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiIHdpZHRoPSIyOHB4IiBoZWlnaHQ9IjE1cHgiIHZpZXdCb3g9IjAgMCAyOCAxNSIgZW5hYmxlLWJhY2tncm91bmQ9Im5ldyAwIDAgMjggMTUiIHhtbDpzcGFjZT0icHJlc2VydmUiPjxwYXRoIGZpbGw9IiNERURFREUiIGQ9Ik0yNy41LDdoLTZDMjEuMiwzLjEsMTgsMCwxNCwwUzYuOCwzLjEsNi41LDdoLTZDMC4yLDcsMCw3LjIsMCw3LjVTMC4yLDgsMC41LDhoNmMwLjMsMy45LDMuNSw3LDcuNSw3czcuMi0zLjEsNy41LTdoNkMyNy44LDgsMjgsNy44LDI4LDcuNVMyNy44LDcsMjcuNSw3eiBNMTQsMWMzLjQsMCw2LjIsMi42LDYuNSw2SDcuNUM3LjgsMy42LDEwLjYsMSwxNCwxeiBNMTQsMTRjLTMuNCwwLTYuMi0yLjYtNi41LTZoMTIuOUMyMC4yLDExLjQsMTcuNCwxNCwxNCwxNHoiLz48L3N2Zz4=);
        background-repeat: no-repeat;
        background-position: center center;
    }

    .card__body {
        font-size: 20px;
        line-height: 1.75;
    }

    /* Modifiers */
    .card:hover {
        cursor: pointer;
        transform: scale(1.05);
    }

        .card:hover .card__wrapper {
            box-shadow: 0 0 10px 0 rgba(0,0,0,.05);
        }

            .card:hover .card__wrapper:after {
                transform: scale(0.95) translateY(10px);
            }

    /* Demo */
    body {
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        background-color: #e9ebea;
        text-align: center;
    }

    .card {
        display: inline-block;
        margin-top: calc( ( 100vh - 506px ) / 2 );
        margin-right: 15px;
        margin-left: 15px;
        top: 50%;
    }
</style>