RedeSocial/RedeSocial.Web/Controllers/AccountApiController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Storage.Blob;
using RedeSocial.Web.Models.Account;
using WebApp.ApiServices;

namespace  RedeSocial.Web.Controllers

{
    public class AccountApiController : Controller
    {
        private readonly IAccountApi _accountApi;

        public AccountApiController(IAccountApi accountApi)
        {
            _accountApi = accountApi;
        }

        // GET: PaisesController
        public async Task<ActionResult> Index()
        {
            var accounts = await _accountApi.GetAsync();

            return View(accounts);
        }

        // GET: PaisesController/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var viewModel = await _accountApi.GetAsync(id);

            return View(viewModel);
        }

        // GET: PaisesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PaisesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CriarAccountViewModel criarAccountViewModel)
        {
            await _accountApi.PostAsync(criarAccountViewModel);

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: PaisesController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var viewModel = await _accountApi.GetAsyncToEdit(id);

            return View(viewModel);
        }

        // POST: PaisesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, EditarAccountViewModel editarAccountViewModel)
        {
            await _accountApi.EditAsync( id ,editarAccountViewModel);
            try
            {

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: PaisesController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var viewModel = await _accountApi.GetAsyncToDelete(id);

            return View(viewModel);
        }

        // POST: PaisesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, DeletarAccountViewModel deletarAccountViewModel)
        {
            await _accountApi.DeleteAsync(id);
            try
            {
                return RedirectToAction("Login", "Account");
            }
            catch
            {
                return View();
            }
        }
        private string UploadFotoPerfil(IFormFile fotoAccount)
        {


            var reader = fotoAccount.OpenReadStream();
            var cloudStorageAccount = Microsoft.Azure.Storage.CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=redesocialverde;AccountKey=ZkwgagZSBq16yjP/iPVd6228IfEO63Q1+e94/SQ2PbeKSAFiKlyL6N8oU7cfuqVekwNxvrLcdY64VkhlBOgMQw==;EndpointSuffix=core.windows.net");
            var blobClient = cloudStorageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("fotoperfil");
            container.CreateIfNotExists();
            var blob = container.GetBlockBlobReference(Guid.NewGuid().ToString());
            blob.UploadFromStream(reader);
            var destinoDaImagemNaNuvem = blob.Uri.ToString();
            return destinoDaImagemNaNuvem;
        }
    }
}

RedeSocial/RedeSocial.Web/Controllers/PostagemApiController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.Storage.Blob;
using RedeSocial.Domain.Account;
using RedeSocial.Web.Models.PostagemApi;
using Ubiety.Dns.Core;
using WebApp.ApiServices;

namespace  RedeSocial.Web.Controllers

{
    public class PostagemApiController : Controller
    {
        private readonly IPostagemApi _postagemApi;
        private readonly IAccountApi _accountApi;

        public PostagemApiController(IPostagemApi postagemApi, IAccountApi accountapi)
        {
            _postagemApi = postagemApi;
            _accountApi = accountapi;
        }

        // GET: PaisesController
        public async Task<ActionResult> Index(string id)
        {
            var accounts = await _postagemApi.GetAsync();

            return View(accounts);
        }

        


        // GET: PaisesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PaisesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CriarPostagemViewModel criarPostagemViewModel)
        {
            var URLFoto = UploadFotoPerfil(criarPostagemViewModel.fotoPost);
            criarPostagemViewModel.urlFotoPost = URLFoto;
            
            await _postagemApi.PostAsync(criarPostagemViewModel);

            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // GET: PaisesController/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var viewModel = await _postagemApi.GetAsyncToEdit(id);

            return View(viewModel);
        }

        // POST: PaisesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, EditarPostagemViewModel editarPostagemViewModel)
        {
            await _postagemApi.EditAsync( id , editarPostagemViewModel);
            try
            {
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PaisesController/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var separadoid = id.Split("&&");
            var postId = separadoid[0];
            var userId = separadoid[1];
            var viewModel = await _postagemApi.GetAsync(userId, postId);

            return View(viewModel);
        }

        // POST: PaisesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, Postagem postagem)
        {
            var separadoid = id.Split("&&");
            var postId = separadoid[0];
            var userId = separadoid[1];
            await _postagemApi.DeleteAsync(userId, postId);
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        private string UploadFotoPerfil(IFormFile fotoPost)
        {


            var reader = fotoPost.OpenReadStream();
            var cloudStorageAccount = Microsoft.Azure.Storage.CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=redesocialverde;AccountKey=ZkwgagZSBq16yjP/iPVd6228IfEO63Q1+e94/SQ2PbeKSAFiKlyL6N8oU7cfuqVekwNxvrLcdY64VkhlBOgMQw==;EndpointSuffix=core.windows.net");
            var blobClient = cloudStorageAccount.CreateCloudBlobClient();
            var container = blobClient.GetContainerReference("fotoperfil");
            container.CreateIfNotExists();
            var blob = container.GetBlockBlobReference(Guid.NewGuid().ToString());
            blob.UploadFromStream(reader);
            var destinoDaImagemNaNuvem = blob.Uri.ToString();
            return destinoDaImagemNaNuvem;
        }
    }
}

RedeSocial/RedeSocial.Web/Views/Shared/_HelloUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="text-center">
    <h2>Hoje é @DateTime.Now.ToString("dd/MM/yyyy") </h2>
  

</div>

RedeSocial/RedeSocial.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RedeSocial.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @if (this.User.Identity.IsAuthenticated)
    {
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Rede Social</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" asp-action="Index" asp-controller="Home">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="PostagemApi">Posts</a>
                        </li>
                    </ul>
                    <form method="post" asp-controller="Account" asp-action="Logout">
                        <input type="submit" value="Logout" />
                    </form>
                    <div class="navbar-text">
                        <img class="img-profile rounded-circle" style="max-width:26px" src="https://redesocialverde.blob.core.windows.net/imagens/@(this.User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.Name).Value)fotoperfil.jpg?size=30x30&bgset=bg1">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">@this.User.Identity.Name.ToLower()</span>
                        <a asp-controller="AccountApi" asp-action="Edit" asp-route-id="@(this.User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value)">Editar Perfil</a>
                    </div>
                </div>
            </nav>
        </header>
    }
    

    <div class="container">
        <main role="main" class="pb-3">
            <!-- AQUI VAI SER RENDERIZADO O HTML DAS VIEWS-->
            @RenderBody()
        </main>
    </div>

    @RenderSection("PreFooter", false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>